name: Debricked Vulnerability Scan
author: Debricked
description: Integrates with Debricked to automatically scan your dependencies for vulnerabilities and license risks
runs:
  using: docker
  image: docker://debricked/debricked-scan
  entrypoint: /github-action.sh
  env:
    SKIP_SCAN: 'true'
branding:
  color: purple
  icon: search
